// Central lib barrel for @/lib and @lib resolvers
export * from './utils'
export * from './cva'
export * from './rate-limit'
export * from './retry-utils'
// Avoid duplicate symbol re-exports between './errors' and './error-handler'
export * from './errors'
export { createError, handleApiError, formatErrorForUser, logError as logApiError, CommonErrors, retryWithBackoff, createErrorMessage, parseError, safeErrorHandler, safeAsyncHandler } from './error-handler'
export * from './seo'
export * from './seo-utils'
export * from './seo-config'
// Export design-related modules carefully to avoid name collisions
export * from './design-system'
export { uiUxFramework } from './ui-ux-framework'
export { campusAxisStandards } from './campusaxis-standards'
export * from './filter-data'
export * from './filter-persistence'
export * from './glassmorphism-2025'
export * from './icon-generator'
export * from './media-upload'
export * from './site-map'
export * from './user-campus-detector'
